/**
 * Task: t7
 * Type: single_pool_with_correct_flags_and_resolved_form
 * Title: Выбери слова, где нужно вставить букву Я
 * Clarification: среди вариантов слов на А должны быть только с Ч и Щ
 * Clarification: существительные только в именительном падеже единственного числа; глаголы только в неопределённой форме (инфинитив)
 * Clarification: не нужны слова, в которых Я в суффиксе (например, -ять / -ать)
 * Constraints: {"total":6,"correct":4,"incorrect":2}
 */
export const taskT7 = {
  "meta": {
    "title": "Выбери слова, где нужно вставить букву Я",
    "type": "single_pool_with_correct_flags_and_resolved_form",
    "constraints": {
      "total": 6,
      "correct": 4,
      "incorrect": 2
    }
  },
  "items": [
    { "id": "t7-1", "text": "за_ц", "correct": true, "answer": "заяц" },
    { "id": "t7-2", "text": "р_д", "correct": true, "answer": "ряд" },
    { "id": "t7-3", "text": "пл_ж", "correct": true, "answer": "пляж" },
    { "id": "t7-4", "text": "_ма", "correct": true, "answer": "яма" },
    { "id": "t7-5", "text": "р_бина", "correct": true, "answer": "рябина" },
    { "id": "t7-6", "text": "м_ч", "correct": true, "answer": "мяч" },
    { "id": "t7-7", "text": "_блоко", "correct": true, "answer": "яблоко" },
    { "id": "t7-8", "text": "_корь", "correct": true, "answer": "якорь" },
    { "id": "t7-9", "text": "_щик", "correct": true, "answer": "ящик" },
    { "id": "t7-10", "text": "_стреб", "correct": true, "answer": "ястреб" },
    { "id": "t7-11", "text": "п_тка", "correct": true, "answer": "пятка" },
    { "id": "t7-12", "text": "п_тно", "correct": true, "answer": "пятно" },
    { "id": "t7-13", "text": "тр_пка", "correct": true, "answer": "тряпка" },
    { "id": "t7-14", "text": "гр_дка", "correct": true, "answer": "грядка" },
    { "id": "t7-15", "text": "_года", "correct": true, "answer": "ягода" },
    { "id": "t7-16", "text": "м_со", "correct": true, "answer": "мясо" },
    { "id": "t7-17", "text": "м_та", "correct": true, "answer": "мята" },
    { "id": "t7-18", "text": "л_гушка", "correct": true, "answer": "лягушка" },
    { "id": "t7-19", "text": "п_так", "correct": true, "answer": "пятак" },
    { "id": "t7-20", "text": "д_тел", "correct": true, "answer": "дятел" },
    { "id": "t7-21", "text": "р_бчик", "correct": true, "answer": "рябчик" },
    { "id": "t7-22", "text": "з_блик", "correct": true, "answer": "зяблик" },
    { "id": "t7-23", "text": "св_зь", "correct": true, "answer": "связь" },
    { "id": "t7-24", "text": "гр_зь", "correct": true, "answer": "грязь" },
    { "id": "t7-25", "text": "бан_", "correct": true, "answer": "баня" },
    { "id": "t7-26", "text": "н_ня", "correct": true, "answer": "няня" },
    { "id": "t7-27", "text": "семь_", "correct": true, "answer": "семья" },
    { "id": "t7-28", "text": "земл_", "correct": true, "answer": "земля" },
    { "id": "t7-29", "text": "стать_", "correct": true, "answer": "статья" },
    { "id": "t7-30", "text": "ладь_", "correct": true, "answer": "ладья" },
    { "id": "t7-31", "text": "зар_", "correct": true, "answer": "заря" },
    { "id": "t7-32", "text": "бур_", "correct": true, "answer": "буря" },
    { "id": "t7-33", "text": "ше_", "correct": true, "answer": "шея" },
    { "id": "t7-34", "text": "зме_", "correct": true, "answer": "змея" },
    { "id": "t7-35", "text": "вишн_", "correct": true, "answer": "вишня" },
    { "id": "t7-36", "text": "алле_", "correct": true, "answer": "аллея" },
    { "id": "t7-37", "text": "иде_", "correct": true, "answer": "идея" },
    { "id": "t7-38", "text": "зате_", "correct": true, "answer": "затея" },
    { "id": "t7-39", "text": "галере_", "correct": true, "answer": "галерея" },
    { "id": "t7-40", "text": "батаре_", "correct": true, "answer": "батарея" },
    { "id": "t7-41", "text": "п_тница", "correct": true, "answer": "пятница" },
    { "id": "t7-42", "text": "пр_ник", "correct": true, "answer": "пряник" },
    { "id": "t7-43", "text": "пр_жа", "correct": true, "answer": "пряжа" },
    { "id": "t7-44", "text": "кл_кса", "correct": true, "answer": "клякса" },
    { "id": "t7-45", "text": "кл_тва", "correct": true, "answer": "клятва" },
    { "id": "t7-46", "text": "тр_ска", "correct": true, "answer": "тряска" },
    { "id": "t7-47", "text": "р_бь", "correct": true, "answer": "рябь" },
    { "id": "t7-48", "text": "гр_да", "correct": true, "answer": "гряда" },
    { "id": "t7-49", "text": "т_га", "correct": true, "answer": "тяга" },
    { "id": "t7-50", "text": "т_пка", "correct": true, "answer": "тяпка" },
    { "id": "t7-51", "text": "_рмарка", "correct": true, "answer": "ярмарка" },
    { "id": "t7-52", "text": "_рлык", "correct": true, "answer": "ярлык" },
    { "id": "t7-53", "text": "_дро", "correct": true, "answer": "ядро" },
    { "id": "t7-54", "text": "_гненок", "correct": true, "answer": "ягненок" },
    { "id": "t7-55", "text": "_гуар", "correct": true, "answer": "ягуар" },
    { "id": "t7-56", "text": "_беда", "correct": true, "answer": "ябеда" },
    { "id": "t7-57", "text": "_мка", "correct": true, "answer": "ямка" },
    { "id": "t7-58", "text": "_мщик", "correct": true, "answer": "ямщик" },
    { "id": "t7-59", "text": "_рость", "correct": true, "answer": "ярость" },
    { "id": "t7-61", "text": "ч_йник", "correct": false, "answer": "чайник" },
    { "id": "t7-62", "text": "ч_шка", "correct": false, "answer": "чашка" },
    { "id": "t7-63", "text": "ч_ща", "correct": false, "answer": "чаща" },
    { "id": "t7-64", "text": "ч_йка", "correct": false, "answer": "чайка" },
    { "id": "t7-65", "text": "щ_вель", "correct": false, "answer": "щавель" },
    { "id": "t7-66", "text": "кач_лка", "correct": false, "answer": "качалка" },
    { "id": "t7-67", "text": "ч_й", "correct": false, "answer": "чай" },
    { "id": "t7-68", "text": "ч_сть", "correct": false, "answer": "часть" },
    { "id": "t7-69", "text": "печ_ть", "correct": false, "answer": "печать" },
    { "id": "t7-70", "text": "ч_ша", "correct": false, "answer": "чаша" },
    { "id": "t7-71", "text": "ч_стица", "correct": false, "answer": "частица" },
    { "id": "t7-72", "text": "рощ_", "correct": false, "answer": "роща" },
    { "id": "t7-73", "text": "дач_", "correct": false, "answer": "дача" },
    { "id": "t7-74", "text": "задач_", "correct": false, "answer": "задача" },
    { "id": "t7-75", "text": "удач_", "correct": false, "answer": "удача" },
    { "id": "t7-76", "text": "подач_", "correct": false, "answer": "подача" },
    { "id": "t7-77", "text": "передач_", "correct": false, "answer": "передача" },
    { "id": "t7-78", "text": "свеч_", "correct": false, "answer": "свеча" },
    { "id": "t7-79", "text": "туч_", "correct": false, "answer": "туча" },
    { "id": "t7-80", "text": "саранч_", "correct": false, "answer": "саранча" },
    { "id": "t7-81", "text": "ч_стота", "correct": false, "answer": "частота" },
    { "id": "t7-82", "text": "ч_стушка", "correct": false, "answer": "частушка" },
    { "id": "t7-83", "text": "прич_л", "correct": false, "answer": "причал" },
    { "id": "t7-84", "text": "оч_г", "correct": false, "answer": "очаг" },
    { "id": "t7-85", "text": "рыч_г", "correct": false, "answer": "рычаг" },
    { "id": "t7-86", "text": "коч_н", "correct": false, "answer": "кочан" },
    { "id": "t7-87", "text": "молч_ть", "correct": false, "answer": "молчать" },
    { "id": "t7-88", "text": "крич_ть", "correct": false, "answer": "кричать" },
    { "id": "t7-89", "text": "стуч_ть", "correct": false, "answer": "стучать" },
    { "id": "t7-90", "text": "кач_ть", "correct": false, "answer": "качать" },
    { "id": "t7-91", "text": "нач_ть", "correct": false, "answer": "начать" },
    { "id": "t7-92", "text": "прощ_ть", "correct": false, "answer": "прощать" },
    { "id": "t7-93", "text": "щ_дить", "correct": false, "answer": "щадить" },
    { "id": "t7-94", "text": "перч_тка", "correct": false, "answer": "перчатка" },
    { "id": "t7-95", "text": "ч_инка", "correct": false, "answer": "чаинка" },
    { "id": "t7-98", "text": "моч_лка", "correct": false, "answer": "мочалка" },
    { "id": "t7-99", "text": "площ_дь", "correct": false, "answer": "площадь" },
    { "id": "t7-100", "text": "площ_дка", "correct": false, "answer": "площадка" }
  ]
};
